basePath: /user
definitions:
  model.User:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      user_number:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  title: User API documentation
  version: 1.0.0
paths:
  /:
    get:
      description: get all users
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Bad Request
          schema:
            type: object
      summary: Create new user based on paramters
      tags:
      - Users
  /{id}:
    get:
      description: get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Bad Request
          schema:
            type: object
      summary: Get one user
      tags:
      - Users
swagger: "2.0"